##### Syslog #####

# The syslog message consists of three parts: PRI (a calculated priority value), HEADER (with identifying information), and MSG (the message itself).
# The PRI data sent via the syslog protocol comes from two numeric values that help categorize the message. The first is the Facility value. This value is one of 15 predefined values or various locally defined values in the case of 16 to 23. These values categorize the type of message or which system generated the event.

Number	Facility description
0		Kernel messages
1		User-level messages
2		Mail System
3		System Daemons
4		Security/Authorization Messages
5		Messages generated by syslogd
6		Line Printer Subsystem
7		Network News Subsystem
8		UUCP Subsystem
9		Clock Daemon
10		Security/Authorization Messages
11		FTP Daemon
12		NTP Subsystem
13		Log Audit
14		Log Alert
15		Clock Daemon
16-23	Local Use 0 - 7

# The second label of a syslog message categorizes the importance or severity of the message in a numerical code from 0 to 7.

Code 	Severity		Description
0		Emergency		System is unusable
1		Alert			Action must be taken immediately
2		Critical		Critical conditions
3		Error			Error conditions
4		Warning			Warning conditions
5		Notice			Normal but significant condition
6		Informational	Informational messages
7		Debug			Debug-level messages

# The values of both labels do not have hard definitions. Thus, it is up to the system or application to determine how to log an event (for example, as a warning, notice, or something else) and on which facility. Within the same application or service, lower numbers should correspond to more severe issues relative to the specific process.
# The two values are combined to produce a Priority Value sent with the message. The Priority Value is calculated by multiplying the Facility value by eight and then adding the Severity Value to the result. The lower the PRI, the higher the priority.

(Facility Value * 8) + Severity Value = PRI

# To output log levels in messages (technically known as priorities), you should change the default template used by rsyslog.
# Open with admin privileges the file /etc/rsyslog.conf and add the following lines:

vim /etc/rsyslog.conf

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat
$template precise,"%PRI% %timegenerated% %HOSTNAME% %syslogtag% %msg%\n"
# $template precise,%syslogpriority% %syslogfacility% %timegenerated% %HOSTNAME% %syslogtag% %msg%\n"
$ActionFileDefaultTemplate precise

# Restart the daemon

service rsyslog restart

# The new output is:

30 Aug  8 07:41:54 uk1lv8438 systemd: Stopping System Logging Service...
46 Aug  8 07:41:54 uk1lv8438 rsyslogd:  [origin software='rsyslogd' swVersion='8.24.0' x-pid='3218' x-info='http://www.rsyslog.com'] exiting on signal 15.
30 Aug  8 07:41:54 uk1lv8438 systemd: Starting System Logging Service...
46 Aug  8 07:41:54 uk1lv8438 rsyslogd:  [origin software='rsyslogd' swVersion='8.24.0' x-pid='3332' x-info='http://www.rsyslog.com'] start


# PRI to get:
[0 - 6]			 0 1 2 3 4 5 6
[8 - 14]		 8 9 10 11 12 13 14
[24 - 30]		 24 25 26 27 28 29 30
[32 - 38]		 32 33 34 35 36 37 38
[56 - 62]		 56 57 58 59 60 61 62
[80 - 86]		 80 81 82 83 84 85 86
[104 - 110]		 104 105 106 107 108 109 110

# Regular expression for Filebeat:
^!\d{3}[0-6]
^!\d{3}[8-9]|1[0-4]
^!\d{3}2[4-9]|3[0]
^!\d{3}3[2-8]
^!\d{3}5[6-9]|6[0-2]
^!\d{3}8[0-6]
^!\d{3}10[4-9]|11[0]

# Filebeat syntax:
include_lines: ['^\d{3}[0-6]', '^\d{3}[8-9]|1[0-4]', '^\d{3}2[4-9]|3[0-9]', '^\d{3}5[6-9]|6[0-2]', '^\d{3}8[0-6]', '^\d{3}10[4-9]|11[0]']
exclude_lines: ['^\d{3}7[0-9]', '^\d{3}9[0-9]', '^\d{3}11[1-9]|19[0-1]']